
/* TPC user */
CREATE USER TPCUSER identified by "TPCUSER";

GRANT CREATE CONNECTION TO tpcuser;
GRANT CREATE SESSION TO tpcuser;
GRANT CREATE TABLE TO tpcuser;
GRANT SELECT ANY DICTIONARY TO tpcuser;
GRANT CREATE VIEW TO tpcuser;
GRANT CREATE FUNCTION TO tpcuser;
GRANT CREATE SCRIPT TO tpcuser;

GRANT CREATE SCHEMA TO tpcuser;
GRANT SELECT ANY DICTIONARY TO tpcuser;

/* TPC-H schema */
CREATE SCHEMA tpch;
CLOSE SCHEMA;
ALTER SCHEMA tpch CHANGE OWNER tpcuser;
--GRANT ALL PRIVILEGES ON SCHEMA tpch TO tpcuser;

commit;
