
ALTER TABLE TPCH.NATION   MODIFY PRIMARY KEY disable;
ALTER TABLE TPCH.SUPPLIER MODIFY PRIMARY KEY disable;
ALTER TABLE TPCH.PARTSUPP MODIFY PRIMARY KEY disable;
ALTER TABLE TPCH.PARTSUPP MODIFY PRIMARY KEY disable;
ALTER TABLE TPCH.CUSTOMER MODIFY PRIMARY KEY disable;
ALTER TABLE TPCH.ORDERS   MODIFY PRIMARY KEY disable;
ALTER TABLE TPCH.LINEITEM MODIFY PRIMARY KEY disable;
ALTER TABLE TPCH.LINEITEM MODIFY PRIMARY KEY disable;

ALTER TABLE TPCH.NATION   MODIFY CONSTRAINT FK_REGION disable;
ALTER TABLE TPCH.SUPPLIER MODIFY CONSTRAINT FK_NATION disable;
ALTER TABLE TPCH.PARTSUPP MODIFY CONSTRAINT FK_PART disable;
ALTER TABLE TPCH.PARTSUPP MODIFY CONSTRAINT FK_SUPP disable;
ALTER TABLE TPCH.CUSTOMER MODIFY CONSTRAINT FK_NATION disable;
ALTER TABLE TPCH.ORDERS   MODIFY CONSTRAINT FK_CUSTOMER disable;
ALTER TABLE TPCH.LINEITEM MODIFY CONSTRAINT FK_ORDER disable;
ALTER TABLE TPCH.LINEITEM MODIFY CONSTRAINT FK_PARTSUPP disable;

TRUNCATE TABLE TPCH.nation;
TRUNCATE TABLE TPCH.region;
TRUNCATE TABLE TPCH.part;
TRUNCATE TABLE TPCH.supplier;
TRUNCATE TABLE TPCH.partsupp;
TRUNCATE TABLE TPCH.customer;
TRUNCATE TABLE TPCH.orders;
TRUNCATE TABLE TPCH.lineitem;

IMPORT INTO TPCH.nation FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.nation.csv'     SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';
IMPORT INTO TPCH.region FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.region.csv'     SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';
IMPORT INTO TPCH.part FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.part.csv'         SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';
IMPORT INTO TPCH.supplier FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.supplier.csv' SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';
IMPORT INTO TPCH.partsupp FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.partsupp.csv' SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';
IMPORT INTO TPCH.customer FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.customer.csv' SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';
IMPORT INTO TPCH.orders FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.orders.csv'     SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';
IMPORT INTO TPCH.lineitem FROM LOCAL CSV FILE 'U:\data_cpn\Documents\OTH\_gitRepos\cyberlytics-primers\primer-bigdata\exasol-sql-TPCH-Query1\data\tpch_1g.lineitem.csv' SKIP = 1 ENCODING = 'UTF8' ROW SEPARATOR = 'LF' COLUMN SEPARATOR = ',' COLUMN DELIMITER = '"';

ALTER TABLE TPCH.NATION   MODIFY PRIMARY KEY enable;
ALTER TABLE TPCH.SUPPLIER MODIFY PRIMARY KEY enable;
ALTER TABLE TPCH.PARTSUPP MODIFY PRIMARY KEY enable;
ALTER TABLE TPCH.PARTSUPP MODIFY PRIMARY KEY enable;
ALTER TABLE TPCH.CUSTOMER MODIFY PRIMARY KEY enable;
ALTER TABLE TPCH.ORDERS   MODIFY PRIMARY KEY enable;
ALTER TABLE TPCH.LINEITEM MODIFY PRIMARY KEY enable;
ALTER TABLE TPCH.LINEITEM MODIFY PRIMARY KEY enable;

ALTER TABLE TPCH.NATION   MODIFY CONSTRAINT FK_REGION enable;
ALTER TABLE TPCH.SUPPLIER MODIFY CONSTRAINT FK_NATION enable;
ALTER TABLE TPCH.PARTSUPP MODIFY CONSTRAINT FK_PART enable;
ALTER TABLE TPCH.PARTSUPP MODIFY CONSTRAINT FK_SUPP enable;
ALTER TABLE TPCH.CUSTOMER MODIFY CONSTRAINT FK_NATION enable;
ALTER TABLE TPCH.ORDERS   MODIFY CONSTRAINT FK_CUSTOMER enable;
ALTER TABLE TPCH.LINEITEM MODIFY CONSTRAINT FK_ORDER enable;
ALTER TABLE TPCH.LINEITEM MODIFY CONSTRAINT FK_PARTSUPP enable;

commit;