
/* TPC user */
CREATE USER DATASCIENTIST identified by "DATASCIENTIST";

GRANT CREATE CONNECTION TO DATASCIENTIST;
GRANT CREATE SESSION TO DATASCIENTIST;
GRANT CREATE TABLE TO DATASCIENTIST;
GRANT SELECT ANY DICTIONARY TO DATASCIENTIST;
GRANT CREATE VIEW TO DATASCIENTIST;
GRANT CREATE FUNCTION TO DATASCIENTIST;
GRANT CREATE SCRIPT TO DATASCIENTIST;

GRANT CREATE SCHEMA TO DATASCIENTIST;
GRANT SELECT ANY DICTIONARY TO DATASCIENTIST;

/* TPC-H schema */
CREATE SCHEMA bible;
CLOSE SCHEMA;
ALTER SCHEMA bible CHANGE OWNER DATASCIENTIST;
--GRANT ALL PRIVILEGES ON SCHEMA bible TO DATASCIENTIST;

commit;
